### ISSUE TITLE
error[E0658]: use of unstable library feature 'try_from' (see issue #33417)

### ISSUE THREAD

**Issue by digiwizkid** [hecrj/wgpu_glyph#3]
<pre><font color="#EF2929"><b>error[E0658]</b></font><b>: use of unstable library feature &apos;try_from&apos; (see issue #33417)</b></pre>

Getting this while trying to run the example.

`cargo run --example hello --features wgpu/vulkan --release`

**Comment by hecrj** [comment]
Which version of Rust are you using? `try_from` was stabilized a while ago: https://github.com/rust-lang/rust/issues/33417

Try running `rustup update` and run the example again. Let me know how that goes!

**Comment by digiwizkid** [comment]
I was using 1.33.0 after updating to 1.35.0, it's working fine.
